name: without_database
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  assets_audio_player: 
    git:
      url: https://github.com/FlutterFlow/Flutter-AssetsAudioPlayer.git
      ref: 243f9533279b73fa9dae345cc96e5d7d84cac0ac
  assets_audio_player_web: 
    git:
      url: https://github.com/FlutterFlow/Flutter-AssetsAudioPlayerWeb.git
      ref: cae7ceb6af99f4da1ec27136d312d0ef045c83d9
  auto_size_text: 3.0.0
  barcode_widget: 2.0.3
  cached_network_image: 3.4.1
  cached_network_image_platform_interface: 4.1.1
  cached_network_image_web: 1.3.1
  collection: 1.19.1
  floating_bottom_navigation_bar: 1.5.2
  flutter_animate: 4.5.0
  flutter_cache_manager: 3.4.1
  font_awesome_flutter: 10.7.0
  from_css_color: 2.0.0
  go_router: 12.1.3
  google_fonts: ^6.1.0
  intl: 0.20.2
  json_path: 0.7.2
  mapbox_search: 4.2.2
  page_transition: 2.1.0
  path_provider: 2.1.4
  path_provider_android: 2.2.10
  path_provider_foundation: 2.4.0
  path_provider_linux: 2.2.1
  path_provider_platform_interface: 2.1.2
  path_provider_windows: 2.3.0
  percent_indicator: 4.2.2
  provider: 6.1.5
  rxdart: 0.27.7
  shared_preferences: 2.5.3
  shared_preferences_android: 2.4.10
  shared_preferences_foundation: 2.5.4
  shared_preferences_linux: 2.4.1
  shared_preferences_platform_interface: 2.4.1
  shared_preferences_web: 2.4.3
  shared_preferences_windows: 2.4.1
  sqflite: 2.3.3+1
  sqflite_common: 2.5.4+3
  timeago: 3.7.1
  url_launcher: 6.3.1
  url_launcher_android: 6.3.16
  url_launcher_ios: 6.3.3
  url_launcher_linux: 3.2.1
  url_launcher_macos: 3.2.2
  url_launcher_platform_interface: 2.3.2
  url_launcher_web: 2.4.1
  url_launcher_windows: 3.1.4
  supabase_flutter: ^2.0.0
  mobile_scanner: ^5.0.0
  permission_handler: ^11.0.0
  geolocator: ^10.1.0
  geocoding: ^3.0.0
  device_apps: ^2.2.0
  call_log: ^6.0.1
  google_maps_flutter: ^2.5.3
  location: ^5.0.3
  cupertino_icons: ^1.0.0

dependency_overrides:
  http: 1.4.0
  uuid: ^4.0.0

dev_dependencies:
  flutter_lints: 4.0.0
  lints: 4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/Poppins-Regular.ttf
    - assets/fonts/Poppins-SemiBold.ttf


